# Site
title:              adetiaraputri
bio:                Collage Student <a href="http://sif.uin-suska.ac.id">Information System</a>, <a href="http://uin-suska.ac.id/">Uin Suska Riau</a>
description:        "welcome to my GitHub Pages"
reading_time:       true
words_per_minute:   200
logo:               'kecil.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://adetiaraputri.github.io
baseurl:            /adetiaraputri.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   adetiaraputri

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            Ade Tiara Putri
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              adetiaraputri18@gmail.com
#twitter:            username
facebook:           adetiaraputri
github:             adetiaraputri
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          putri.adetiara
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
